apiVersion: apps/v1
kind: Deployment
metadata:
 # annotations: 
  #  deployment.kubernetes.io/revision: "2"
   # kubernetes.io/change-cause: "Changed to nginx:1.23.1"
  creationTimestamp: null
  labels:
    app: web-app
  name: web-app
spec:
  replicas: 6
  selector:
    matchLabels:
      app: web-app
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: web-app
    spec:
      containers:
      - image: nginx:1.23.1-alpine
        name: nginx
        resources: {}
status: {}